export const TRADUCTIONS_ANGLAIS = {
  // Header & Navigation
  nomEtablissement: 'Saint Jude Academy',
  sousTitreEtablissement: 'Academic & Administrative System',
  recherchePlaceholder: 'Search students, teachers, invoices, books...',
  noticesEtBulletins: 'Notices & Bulletins',
  fermer: 'Close',
  changerRole: 'Switch Workspace Role',
  anneeScolaire: 'Academic Year 2025–2026',
  trimestreActif: 'Term 2 Active',
  droitsReserves: 'All rights reserved.',
  editionEntreprise: 'Academic Management Portal • Enterprise Edition',

  // Roles
  role_administrateur: 'Headmaster / Director',
  role_professeur: 'Faculty & Teacher',
  role_eleve: 'Student Portal',
  role_parent: 'Parent & Guardian',
  role_secretaire: 'Secretary & Admissions',
  role_comptable: 'Finance & Bursar',
  role_ressources_humaines: 'Human Resources',
  role_bibliothecaire: 'Librarian',
  role_charge_communication: 'Communications',

  // Modules
  module_tableau_de_bord: 'Overview Dashboard',
  module_administration: 'Administration',
  module_professeurs: 'Faculty & Teachers',
  module_eleves: 'Student Records',
  module_parents: 'Parent Portal',
  module_comptabilite: 'Accounting & Fees',
  module_ressources_humaines: 'Human Resources',
  module_bibliotheque: 'Library Catalog',
  module_communication: 'Communications',

  // Navigation contextuelle par role
  menu_tableau_de_bord: 'Dashboard',
  menu_administration: 'Administration',
  menu_comptabilite_frais: 'Accounting & Fees',
  menu_ressources_humaines: 'Human Resources',
  menu_communications: 'Communications',
  menu_mes_classes: 'My Classes',
  menu_grading_marks: 'Grading & Marks',
  menu_ressources_pedagogiques: 'Teaching Resources',
  menu_mes_cours: 'My Courses',
  menu_mes_notes: 'My Grades',
  menu_devoirs_examens: 'Homework & Exams',
  menu_ressources_eleves: 'Student Resources',
  menu_suivi_enfant: 'Child Monitoring',
  menu_absences_justificatifs: 'Absences & Excuses',
  menu_moyennes_resultats: 'Grades & Results',
  menu_dossiers_eleves: 'Student Records',
  menu_inscriptions: 'Admissions',
  menu_calendrier_horaires: 'Timetable & Schedule',
  menu_administratif: 'Administrative',
  menu_budgets: 'Budgets',
  menu_rapports_financiers: 'Financial Reports',
  menu_paie: 'Payroll',
  menu_gestion_personnel: 'Staff Management',
  menu_catalogue_bibliotheque: 'Library Catalog',
  menu_emprunts_retours: 'Loans & Returns',
  menu_ressources_numeriques: 'Digital Resources',
  menu_actualites: 'News',
  menu_annonces: 'Announcements',
  menu_medias: 'Media',

  // Common Buttons
  enregistrer: 'Save Record',
  annuler: 'Cancel',
  voirTout: 'View All',
  ajouter: 'Add',
  rechercher: 'Search',
  payer: 'Pay',
  envoyer: 'Send',
  approuver: 'Approve',
  rejeter: 'Reject',
  rendreLivre: 'Mark as Returned',

  // Dashboard
  titreTableauDeBord: 'Academic Operations Dashboard',
  descriptionTableauDeBord: 'Real-time status across students, faculty, finances, and campus infrastructure.',
  nouvelleInscription: 'New Enrollment',
  elevesInscrits: 'Enrolled Students',
  repartitionCohortes: 'Active across 4 cohorts',
  corpsEnseignant: 'Faculty Members',
  enseignantsComplets: 'Teaching full curriculum',
  recouvrementFrais: 'Fee Collection',
  tauxDeRecouvrement: 'collection rate',
  inventaireBibliotheque: 'Library Inventory',
  exemplairesEnRayon: 'Copies currently on shelves',
  emploiDuTempsDuJour: "Today's Class Schedule",
  horairesEtSalles: 'Live lecture timetables and venues',
  avisOfficiels: 'Official Notices',
  enDirect: 'Live',
  ouvrirCommunication: 'Open Communications Desk',

  // Administration
  titreAdministration: 'Institutional Administration',
  descriptionAdministration: 'Configure academic cohorts, faculty assignments, credentials, and institutional policies.',
  parametresAcademiques: 'Academic Settings',
  sessionAcademique: 'Academic Term',
  cohortesActives: 'Active Cohorts',
  capaciteCohortes: '4 Classes • 108 Capacity',
  conformiteSecurite: 'Security Compliance',
  normeSecurite: 'ISO-27001 Verified',
  repartitionClassesTitre: 'Cohort & Class Distribution',
  repartitionClassesDesc: 'Classrooms, allocated homeroom tutors, and student quotas',
  classeCohorte: 'Cohort Class',
  salleAssignee: 'Assigned Venue',
  professeurPrincipal: 'Homeroom Tutor',
  effectifEleves: 'Students Count',
  statut: 'Status',
  actif: 'Active',

  // Faculty & Grades
  titreProfesseurs: 'Faculty & Gradebook Desk',
  descriptionProfesseurs: 'Submit student test marks, track lecture roll-calls, and manage pedagogical assessments.',
  faireAppel: 'Mark Attendance',
  saisirNote: 'Enter Assessment Grade',
  registreNotes: 'Student Gradebook Registry',
  registreNotesDesc: 'Continuous assessments, lab grades, and midterm tests',
  toutesLesClasses: 'All Cohorts',
  nomEleve: 'Student Name',
  classe: 'Class Cohort',
  matiereEtTitre: 'Subject & Title',
  note: 'Score',
  date: 'Date',
  appreciation: 'Teacher Feedback',
  aucuneAppreciation: 'No feedback recorded.',

  // Students
  titreEleves: 'Student Enrolment & Directory',
  descriptionEleves: 'Complete student profiles, academic averages, parent contacts, and fee status.',
  inscrireNouvelEleve: 'Register New Student',
  effectifInscrit: 'Enrolled Student Cohort',
  rechercheMatricule: 'Search matricule or name...',
  matriculeEtNom: 'Matricule & Name',
  contactParent: 'Guardian Contact',
  moyenneGenerale: 'Academic Average',
  presence: 'Attendance',
  statutScolarite: 'Fee Status',
  soldeRegle: 'Paid in Full',
  soldePartiel: 'Partial Balance',
  enRetard: 'Overdue',

  // Parents
  titreParents: 'Parent & Guardian Portal',
  descriptionParents: 'Real-time grades, attendance monitoring, and direct school tuition payments.',
  eleveSelectionne: 'Active Student:',
  contacterProfesseur: 'Message Faculty',
  derniersResultats: 'Recent Academic Test Results',
  relevesFrais: 'Tuition & School Fee Statements',
  echeanceLe: 'Due by',
  resteAPayer: 'Balance:',
  payerFrais: 'Pay Tuition Balance',

  // Accounting
  titreComptabilite: 'Finance & Bursar Management',
  descriptionComptabilite: 'Tuition receivables, institutional disbursements, invoice billing, and general ledgers.',
  enregistrerTransaction: 'Record Transaction',
  genererFacture: 'Generate Student Invoice',
  totalFacture: 'Total Invoiced',
  recettesEncaissees: 'Collected Revenue',
  impayesRestants: 'Outstanding Balances',
  facturesEleves: 'Student Tuition Invoices',
  journalFinancier: 'General Financial Ledger',
  type: 'Type',
  categorie: 'Category',
  montant: 'Amount',
  depense: 'Expenditure',
  revenu: 'Income',

  // HR
  titreRH: 'Human Resources & Staffing',
  descriptionRH: 'Faculty contracts, monthly payroll summaries, and employee leave requests.',
  demanderConge: 'Request Leave',
  ajouterPersonnel: 'Add Staff Member',
  personnelActif: 'Active Staff',
  masseSalariale: 'Monthly Payroll',
  congesEnAttente: 'Pending Leaves',
  annuairePersonnel: 'Faculty & Personnel Directory',
  posteEtDepartement: 'Role & Dept',
  contrat: 'Contract',
  salaireMensuel: 'Monthly Salary',
  demandesCongesTitre: 'Leave & Time-Off Requests',

  // Library
  titreBibliotheque: 'Library & Learning Resources',
  descriptionBibliotheque: 'Book catalog index, student borrowing logs, and shelf inventory tracking.',
  nouvelEmprunt: 'Issue Book Loan',
  ajouterLivre: 'Add New Book',
  totalOuvrages: 'Total Collection',
  exemplairesDispo: 'Available on Shelves',
  empruntsActifs: 'Active Book Loans',
  catalogueLivres: 'Library Book Catalog',
  rechercheLivre: 'Search title, author or ISBN...',
  titreEtAuteur: 'Book Title & Author',
  emplacement: 'Location',
  disponibilite: 'Available Copies',
  suiviEmprunts: 'Active Book Borrowings',
  emprunteur: 'Borrower',
  dateRetourPrevue: 'Due Date',
  titre: 'Title',
  auteur: 'Author',
  catalogueOuvrages: 'Book Catalogue',
  exemplairesDisponibles: 'Available Copies',
  disponible: 'available',
  empruntsEnCours: 'Current Loans',
  emprunterLivre: 'Issue Book Loan',
  fondsDocumentaire: 'Collection Library',
  disponiblesEnRayon: 'Available on Shelf',
  nombreTotalExemplaires: 'Total Copies',

  // Communication
  titreCommunication: 'Institutional Communications & Broadcasts',
  descriptionCommunication: 'Dispatch announcements, circulars, urgent alerts, and event notifications across campus channels.',
  nouvelleCirculaire: 'Publish New Circular',
  bulletinsActifs: 'Active Bulletins',
  diffusionsParents: 'Parent Broadcasts',
  alertesUrgentes: 'Emergency Dispatches',
  filCirculaires: 'Campus Circular Feed',
  publicCible: 'Target Audience:',
  priorite: 'Priority',
  publiePar: 'Issued by:',
  fluxAnnonces: 'Campus Circular Feed',
  publierAnnonce: 'Publish Campus Circular',
  destinataire: 'Audience Target',

  // Role Dashboards
  coursDuJour: "Today's Teaching Schedule",
  evaluationsRecentes: 'Recently Submitted Grades',
  effectifTotalEnseigne: 'Students Under Tutorship',
  classesAssigneesTitre: 'Assigned Classes',
  tauxAssiduiteMoyen: 'Average Attendance Rate',
  mesNotes: 'My Recent Test Scores',
  mesCours: 'My Weekly Timetable',
  mesLivresEmpruntes: 'My Borrowed Library Books',
  fraisScolaires: 'Tuition Fee Status',
  tauxPresence: 'Attendance Rate',
  suiviScolaireEnfant: 'Student Academic Progress',
  reglerSolde: 'Pay Tuition Balance',
  contacterEnseignant: 'Message Homeroom Teacher',
  prochaineEcheance: 'Next Due Date',
  statistiquesFinancieres: 'Overall Financial Summary',
  facturesImpayees: 'Invoices Awaiting Payment',
  dernieresTransactions: 'Recent Financial Transactions',
  tauxPaiement: 'Collection Performance',
  syntheseRH: 'Staffing & Payroll Overview',
  demandesAValider: 'Pending Leave Requests',
  effectifActif: 'Active Staff Headcount',
  masseSalarialeMensuelle: 'Monthly Payroll Total',
  etatFondsDocumentaire: 'Library Stock & Circulation',
  empruntsEnRetardTitre: 'Overdue Book Loans',
  titresPopulaires: 'Volumes in Stock',
  syntheseCommunications: 'Campus Broadcast Center',
  diffusionsRecentes: 'Recent Dispatched Bulletins',
  alertesCritiques: 'Urgent Safety Alerts',
};
