export const TRADUCTIONS_EN_NAVIGATION = {
  // Header & Navigation
  nomEtablissement: 'Saint Jude Academy',
  sousTitreEtablissement: 'Academic & Administrative System',
  recherchePlaceholder: 'Search students, teachers, invoices, books...',
  noticesEtBulletins: 'Notices & Bulletins',
  fermer: 'Close',
  changerRole: 'Switch Workspace Role',
  anneeScolaire: 'Academic Year 2025–2026',
  trimestreActif: 'Term 2 Active',
  droitsReserves: 'All rights reserved.',
  editionEntreprise: 'Academic Management Portal • Enterprise Edition',

  // Roles
  role_administrateur: 'Headmaster / Director',
  role_professeur: 'Faculty & Teacher',
  role_eleve: 'Student Portal',
  role_parent: 'Parent & Guardian',
  role_secretaire: 'Secretary & Admissions',
  role_comptable: 'Finance & Bursar',
  role_ressources_humaines: 'Human Resources',
  role_bibliothecaire: 'Librarian',
  role_charge_communication: 'Communications',

  // Modules
  module_tableau_de_bord: 'Overview Dashboard',
  module_administration: 'Administration',
  module_professeurs: 'Faculty & Teachers',
  module_eleves: 'Student Records',
  module_parents: 'Parent Portal',
  module_comptabilite: 'Accounting & Fees',
  module_ressources_humaines: 'Human Resources',
  module_bibliotheque: 'Library Catalog',
  module_communication: 'Communications',

  // Navigation contextuelle par role
  menu_tableau_de_bord: 'Dashboard',
  menu_administration: 'Administration',
  menu_comptabilite_frais: 'Accounting & Fees',
  menu_ressources_humaines: 'Human Resources',
  menu_communications: 'Communications',
  menu_mes_classes: 'My Classes',
  menu_grading_marks: 'Grading & Marks',
  menu_ressources_pedagogiques: 'Teaching Resources',
  menu_mes_cours: 'My Courses',
  menu_mes_notes: 'My Grades',
  menu_devoirs_examens: 'Homework & Exams',
  menu_ressources_eleves: 'Student Resources',
  menu_suivi_enfant: 'Child Monitoring',
  menu_absences_justificatifs: 'Absences & Excuses',
  menu_moyennes_resultats: 'Grades & Results',
  menu_dossiers_eleves: 'Student Records',
  menu_inscriptions: 'Admissions',
  menu_calendrier_horaires: 'Timetable & Schedule',
  menu_administratif: 'Administrative',
  menu_budgets: 'Budgets',
  menu_rapports_financiers: 'Financial Reports',
  menu_paie: 'Payroll',
  menu_gestion_personnel: 'Staff Management',
  menu_catalogue_bibliotheque: 'Library Catalog',
  menu_emprunts_retours: 'Loans & Returns',
  menu_ressources_numeriques: 'Digital Resources',
  menu_actualites: 'News',
  menu_annonces: 'Announcements',
  menu_medias: 'Media',

  // Common Buttons
  enregistrer: 'Save Record',
  annuler: 'Cancel',
  voirTout: 'View All',
  ajouter: 'Add',
  rechercher: 'Search',
  payer: 'Pay',
  envoyer: 'Send',
  approuver: 'Approve',
  rejeter: 'Reject',
  rendreLivre: 'Mark as Returned',
};
