import { Eleve, Professeur } from '../types';
export { NOTES_INITIALES, PRESENCES_INITIALES } from './donneesEvaluations';

export const ELEVES_INITIAUX: Eleve[] = [
  {
    identifiant: 'el-1',
    matricule: 'STU-2026-001',
    nomComplet: 'Marcus Vance',
    classe: '1ère C',
    dateNaissance: '2009-04-12',
    courriel: 'm.vance@student.academy.edu',
    telephoneParent: '+1 (555) 014-7788',
    nomParent: 'Eleanor Vance',
    statutFrais: 'paye',
    moyenneGenerale: 88.5,
    tauxPresence: 96.2,
  },
  {
    identifiant: 'el-2',
    matricule: 'STU-2026-002',
    nomComplet: 'Sophia Martinez',
    classe: '1ère C',
    dateNaissance: '2009-08-23',
    courriel: 's.martinez@student.academy.edu',
    telephoneParent: '+1 (555) 014-9911',
    nomParent: 'Carlos Martinez',
    statutFrais: 'paye',
    moyenneGenerale: 92.4,
    tauxPresence: 98.5,
  },
  {
    identifiant: 'el-3',
    matricule: 'STU-2026-003',
    nomComplet: "Liam O'Connor",
    classe: '2nde A',
    dateNaissance: '2010-01-15',
    courriel: 'l.oconnor@student.academy.edu',
    telephoneParent: '+1 (555) 014-4422',
    nomParent: "Fiona O'Connor",
    statutFrais: 'partiel',
    moyenneGenerale: 79.1,
    tauxPresence: 91.0,
  },
  {
    identifiant: 'el-4',
    matricule: 'STU-2026-004',
    nomComplet: 'Chloe Dubois',
    classe: 'Tle D',
    dateNaissance: '2008-11-03',
    courriel: 'c.dubois@student.academy.edu',
    telephoneParent: '+1 (555) 014-6633',
    nomParent: 'Henri Dubois',
    statutFrais: 'en_retard',
    moyenneGenerale: 84.8,
    tauxPresence: 94.7,
  },
  {
    identifiant: 'el-5',
    matricule: 'STU-2026-005',
    nomComplet: 'Gabriel Traore',
    classe: '6e A',
    dateNaissance: '2014-06-18',
    courriel: 'g.traore@student.academy.edu',
    telephoneParent: '+1 (555) 014-1122',
    nomParent: 'Amadou Traore',
    statutFrais: 'paye',
    moyenneGenerale: 90.2,
    tauxPresence: 99.0,
  },
  {
    identifiant: 'el-6',
    matricule: 'STU-2026-006',
    nomComplet: 'Emma Watson-Kouassi',
    classe: '5e B',
    dateNaissance: '2013-03-22',
    courriel: 'e.kouassi@student.academy.edu',
    telephoneParent: '+1 (555) 014-3344',
    nomParent: 'Claire Kouassi',
    statutFrais: 'paye',
    moyenneGenerale: 86.4,
    tauxPresence: 95.8,
  },
  {
    identifiant: 'el-7',
    matricule: 'STU-2026-007',
    nomComplet: 'Noah Diallo',
    classe: '4e A',
    dateNaissance: '2012-09-09',
    courriel: 'n.diallo@student.academy.edu',
    telephoneParent: '+1 (555) 014-5566',
    nomParent: 'Ousmane Diallo',
    statutFrais: 'partiel',
    moyenneGenerale: 81.3,
    tauxPresence: 93.4,
  },
  {
    identifiant: 'el-8',
    matricule: 'STU-2026-008',
    nomComplet: 'Amina Diop',
    classe: '3e A',
    dateNaissance: '2011-02-14',
    courriel: 'a.diop@student.academy.edu',
    telephoneParent: '+1 (555) 014-7799',
    nomParent: 'Fatou Diop',
    statutFrais: 'paye',
    moyenneGenerale: 94.6,
    tauxPresence: 97.8,
  },
  {
    identifiant: 'el-9',
    matricule: 'STU-2026-009',
    nomComplet: 'Alexandre Meyer',
    classe: 'Tle C',
    dateNaissance: '2008-05-30',
    courriel: 'a.meyer@student.academy.edu',
    telephoneParent: '+1 (555) 014-8800',
    nomParent: 'Julien Meyer',
    statutFrais: 'paye',
    moyenneGenerale: 95.8,
    tauxPresence: 99.1,
  },
];

export const PROFESSEURS_INITIAUX: Professeur[] = [
  {
    identifiant: 'prof-1',
    matricule: 'TCH-101',
    nomComplet: 'Prof. Evelyn Reed',
    matiere: 'Advanced Mathematics',
    classesAssignees: ['1ère C', 'Tle C', '3e A'],
    courriel: 'e.reed@academy.edu',
    telephone: '+1 (555) 018-9921',
    dateEmbauche: '2019-09-01',
  },
  {
    identifiant: 'prof-2',
    matricule: 'TCH-102',
    nomComplet: 'Dr. Robert Chen',
    matiere: 'Physics & Chemistry',
    classesAssignees: ['2nde C', '1ère C', 'Tle D'],
    courriel: 'r.chen@academy.edu',
    telephone: '+1 (555) 018-7733',
    dateEmbauche: '2020-02-15',
  },
  {
    identifiant: 'prof-3',
    matricule: 'TCH-103',
    nomComplet: 'Sarah Jenkins',
    matiere: 'English & French Literature',
    classesAssignees: ['6e A', '4e A', '2nde A', '1ère A', 'Tle A'],
    courriel: 's.jenkins@academy.edu',
    telephone: '+1 (555) 018-6644',
    dateEmbauche: '2018-08-20',
  },
  {
    identifiant: 'prof-4',
    matricule: 'TCH-104',
    nomComplet: 'M. Jean-Paul Durand',
    matiere: 'Histoire-Géographie & ECM',
    classesAssignees: ['6e A', '5e B', '3e A', '2nde A', 'Tle A'],
    courriel: 'jp.durand@academy.edu',
    telephone: '+1 (555) 018-4455',
    dateEmbauche: '2017-09-01',
  },
  {
    identifiant: 'prof-5',
    matricule: 'TCH-105',
    nomComplet: 'Mme Helene Bamba',
    matiere: 'SVT (Sciences de la Vie et de la Terre)',
    classesAssignees: ['5e B', '3e A', '2nde C', '1ère D', 'Tle D'],
    courriel: 'h.bamba@academy.edu',
    telephone: '+1 (555) 018-3322',
    dateEmbauche: '2021-01-10',
  },
];
