import { NoteEleve, PresenceEleve } from '../types';

export const NOTES_INITIALES: NoteEleve[] = [
  {
    identifiant: 'note-1',
    identifiantEleve: 'el-1',
    nomEleve: 'Marcus Vance',
    classe: '1ère C',
    matiere: 'Advanced Mathematics',
    titreEvaluation: 'Calculus Mid-Term Exam',
    noteObtenue: 91,
    noteMaximale: 100,
    dateEvaluation: '2026-03-10',
    commentaire: 'Excellent mastery of integration techniques.',
  },
  {
    identifiant: 'note-2',
    identifiantEleve: 'el-1',
    nomEleve: 'Marcus Vance',
    classe: '1ère C',
    matiere: 'Physics & Chemistry',
    titreEvaluation: 'Kinematics Lab Report',
    noteObtenue: 86,
    noteMaximale: 100,
    dateEvaluation: '2026-03-05',
    commentaire: 'Great experimental analysis and error margin calculations.',
  },
  {
    identifiant: 'note-3',
    identifiantEleve: 'el-2',
    nomEleve: 'Sophia Martinez',
    classe: '1ère C',
    matiere: 'Advanced Mathematics',
    titreEvaluation: 'Calculus Mid-Term Exam',
    noteObtenue: 96,
    noteMaximale: 100,
    dateEvaluation: '2026-03-10',
    commentaire: 'Top performance in the cohort.',
  },
  {
    identifiant: 'note-4',
    identifiantEleve: 'el-3',
    nomEleve: "Liam O'Connor",
    classe: '2nde A',
    matiere: 'English & French Literature',
    titreEvaluation: 'Essay on Classical Dramaturgy',
    noteObtenue: 78,
    noteMaximale: 100,
    dateEvaluation: '2026-03-08',
    commentaire: 'Solid thematic arguments, enhance syntax refinement.',
  },
  {
    identifiant: 'note-5',
    identifiantEleve: 'el-8',
    nomEleve: 'Amina Diop',
    classe: '3e A',
    matiere: 'Advanced Mathematics',
    titreEvaluation: 'Brevet Blanc - Mathématiques',
    noteObtenue: 98,
    noteMaximale: 100,
    dateEvaluation: '2026-03-11',
    commentaire: 'Remarquable résolution des problèmes géométriques.',
  },
  {
    identifiant: 'note-6',
    identifiantEleve: 'el-9',
    nomEleve: 'Alexandre Meyer',
    classe: 'Tle C',
    matiere: 'Advanced Mathematics',
    titreEvaluation: 'Bac Blanc - Épreuve Spécialité',
    noteObtenue: 97,
    noteMaximale: 100,
    dateEvaluation: '2026-03-09',
    commentaire: 'Excellente rigueur dans les démonstrations.',
  },
];

export const PRESENCES_INITIALES: PresenceEleve[] = [
  {
    identifiant: 'pres-1',
    identifiantEleve: 'el-1',
    nomEleve: 'Marcus Vance',
    classe: '1ère C',
    date: '2026-03-12',
    statut: 'present',
  },
  {
    identifiant: 'pres-2',
    identifiantEleve: 'el-2',
    nomEleve: 'Sophia Martinez',
    classe: '1ère C',
    date: '2026-03-12',
    statut: 'present',
  },
  {
    identifiant: 'pres-3',
    identifiantEleve: 'el-3',
    nomEleve: "Liam O'Connor",
    classe: '2nde A',
    date: '2026-03-12',
    statut: 'retard',
    remarque: 'Late by 10 mins (Traffic bus delay)',
  },
  {
    identifiant: 'pres-4',
    identifiantEleve: 'el-4',
    nomEleve: 'Chloe Dubois',
    classe: 'Tle D',
    date: '2026-03-12',
    statut: 'absent',
    remarque: 'Unexcused morning absence',
  },
  {
    identifiant: 'pres-5',
    identifiantEleve: 'el-5',
    nomEleve: 'Gabriel Traore',
    classe: '6e A',
    date: '2026-03-12',
    statut: 'present',
  },
  {
    identifiant: 'pres-6',
    identifiantEleve: 'el-8',
    nomEleve: 'Amina Diop',
    classe: '3e A',
    date: '2026-03-12',
    statut: 'present',
  },
];
