import { FactureComptabilite, TransactionFinanciere } from '../types';

export const FACTURES_INITIALES: FactureComptabilite[] = [
  {
    identifiant: 'fac-1',
    numeroFacture: 'INV-2026-1044',
    identifiantEleve: 'el-1',
    nomEleve: 'Marcus Vance',
    classe: '1ère C',
    montantTotal: 4500,
    montantPaye: 4500,
    dateEmission: '2026-01-15',
    dateEcheance: '2026-02-15',
    statut: 'paye',
    typePaiement: 'scolarite',
  },
  {
    identifiant: 'fac-2',
    numeroFacture: 'INV-2026-1045',
    identifiantEleve: 'el-3',
    nomEleve: "Liam O'Connor",
    classe: '2nde A',
    montantTotal: 4200,
    montantPaye: 2100,
    dateEmission: '2026-01-15',
    dateEcheance: '2026-03-20',
    statut: 'partiel',
    typePaiement: 'scolarite',
  },
  {
    identifiant: 'fac-3',
    numeroFacture: 'INV-2026-1046',
    identifiantEleve: 'el-4',
    nomEleve: 'Chloe Dubois',
    classe: 'Tle D',
    montantTotal: 1200,
    montantPaye: 0,
    dateEmission: '2026-02-01',
    dateEcheance: '2026-02-28',
    statut: 'en_retard',
    typePaiement: 'transport',
  },
  {
    identifiant: 'fac-4',
    numeroFacture: 'INV-2026-1047',
    identifiantEleve: 'el-5',
    nomEleve: 'Gabriel Traore',
    classe: '6e A',
    montantTotal: 3800,
    montantPaye: 3800,
    dateEmission: '2026-01-10',
    dateEcheance: '2026-02-10',
    statut: 'paye',
    typePaiement: 'scolarite',
  },
  {
    identifiant: 'fac-5',
    numeroFacture: 'INV-2026-1048',
    identifiantEleve: 'el-8',
    nomEleve: 'Amina Diop',
    classe: '3e A',
    montantTotal: 4000,
    montantPaye: 4000,
    dateEmission: '2026-01-12',
    dateEcheance: '2026-02-12',
    statut: 'paye',
    typePaiement: 'scolarite',
  },
];

export const TRANSACTIONS_INITIALES: TransactionFinanciere[] = [
  {
    identifiant: 'tr-1',
    reference: 'TXN-9982',
    type: 'revenu',
    categorie: 'frais_scolaires',
    description: 'Term 2 Secondary Tuition fees receipt (6e à Terminale)',
    montant: 24500,
    dateTransaction: '2026-03-10',
    beneficiaire: 'Academy General Treasury',
  },
  {
    identifiant: 'tr-2',
    reference: 'TXN-9983',
    type: 'depense',
    categorie: 'salaires',
    description: 'Secondary Faculty and Staff Monthly Payroll',
    montant: 42000,
    dateTransaction: '2026-03-01',
    beneficiaire: 'Faculty Staff Direct Bank Wire',
  },
  {
    identifiant: 'tr-3',
    reference: 'TXN-9984',
    type: 'depense',
    categorie: 'equipements',
    description: 'Science Lab Digital Microscopes & Secondary Sensors',
    montant: 6800,
    dateTransaction: '2026-03-07',
    beneficiaire: 'Scientific Instruments Ltd',
  },
];
