import { Utilisateur, CoursHoraire } from '../types';

export const UTILISATEURS_INITIAUX: Utilisateur[] = [
  {
    identifiant: 'u-1',
    nomComplet: 'Dr. Arthur Sterling',
    courriel: 'admin@academy.edu',
    role: 'administrateur',
    telephone: '+1 (555) 019-2834',
    departement: 'Executive Board',
  },
  {
    identifiant: 'u-2',
    nomComplet: 'Prof. Evelyn Reed',
    courriel: 'e.reed@academy.edu',
    role: 'professeur',
    telephone: '+1 (555) 018-9921',
    departement: 'Mathematics & Science',
  },
  {
    identifiant: 'u-3',
    nomComplet: 'Marcus Vance',
    courriel: 'm.vance@student.academy.edu',
    role: 'eleve',
    telephone: '+1 (555) 012-3456',
    departement: '1ère C - Première Scientifique',
  },
  {
    identifiant: 'u-4',
    nomComplet: 'Eleanor Vance',
    courriel: 'eleanor.vance@parent.edu',
    role: 'parent',
    telephone: '+1 (555) 014-7788',
    departement: 'Parent Association',
  },
  {
    identifiant: 'u-5',
    nomComplet: 'David Hawthorne',
    courriel: 'finance@academy.edu',
    role: 'comptable',
    telephone: '+1 (555) 016-5544',
    departement: 'Bursar & Accounting',
  },
  {
    identifiant: 'u-6',
    nomComplet: 'Clara Bennett',
    courriel: 'hr@academy.edu',
    role: 'ressources_humaines',
    telephone: '+1 (555) 017-3322',
    departement: 'Human Resources',
  },
  {
    identifiant: 'u-7',
    nomComplet: 'Hannah Campbell',
    courriel: 'library@academy.edu',
    role: 'bibliothecaire',
    telephone: '+1 (555) 013-1100',
    departement: 'Learning Resource Center',
  },
  {
    identifiant: 'u-8',
    nomComplet: 'Julian Mercer',
    courriel: 'press@academy.edu',
    role: 'charge_communication',
    telephone: '+1 (555) 015-8899',
    departement: 'Communications & Outreach',
  },
];

export const COURS_HORAIRES_INITIAUX: CoursHoraire[] = [
  {
    identifiant: 'crs-1',
    classe: '1ère C',
    matiere: 'Advanced Mathematics',
    professeurNom: 'Prof. Evelyn Reed',
    jourSemaine: 'Monday',
    heureDebut: '08:00',
    heureFin: '10:00',
    salle: 'Room 302',
  },
  {
    identifiant: 'crs-2',
    classe: '1ère C',
    matiere: 'Physics & Chemistry',
    professeurNom: 'Dr. Robert Chen',
    jourSemaine: 'Monday',
    heureDebut: '10:15',
    heureFin: '12:15',
    salle: 'Science Lab B',
  },
  {
    identifiant: 'crs-3',
    classe: '1ère C',
    matiere: 'English & French Literature',
    professeurNom: 'Sarah Jenkins',
    jourSemaine: 'Tuesday',
    heureDebut: '08:00',
    heureFin: '10:00',
    salle: 'Lecture Hall 1',
  },
  {
    identifiant: 'crs-4',
    classe: '6e A',
    matiere: 'Français & Initiation Littéraire',
    professeurNom: 'Sarah Jenkins',
    jourSemaine: 'Monday',
    heureDebut: '08:00',
    heureFin: '09:30',
    salle: 'Room 101',
  },
  {
    identifiant: 'crs-5',
    classe: '3e A',
    matiere: 'Mathématiques & Préparation Brevet',
    professeurNom: 'Prof. Evelyn Reed',
    jourSemaine: 'Tuesday',
    heureDebut: '10:00',
    heureFin: '12:00',
    salle: 'Room 204',
  },
  {
    identifiant: 'crs-6',
    classe: 'Tle C',
    matiere: 'Mathématiques Spécialité Bac',
    professeurNom: 'Prof. Evelyn Reed',
    jourSemaine: 'Wednesday',
    heureDebut: '08:00',
    heureFin: '11:00',
    salle: 'Amphi Sciences',
  },
];
