import {
  EmployeRH,
  DemandeConge,
  LivreBibliotheque,
  EmpruntLivre,
  AnnonceCommunication,
} from '../types';

export const EMPLOYES_INITIAUX: EmployeRH[] = [
  {
    identifiant: 'emp-1',
    matricule: 'EMP-001',
    nomComplet: 'Dr. Arthur Sterling',
    poste: 'Head of School / Director',
    departement: 'Administration',
    typeContrat: 'CDI',
    salaireMensuel: 8500,
    dateDebut: '2016-08-01',
    joursCongesRestants: 22,
    statut: 'actif',
  },
  {
    identifiant: 'emp-2',
    matricule: 'EMP-002',
    nomComplet: 'Prof. Evelyn Reed',
    poste: 'Lead Mathematics Instructor',
    departement: 'Pedagogique',
    typeContrat: 'CDI',
    salaireMensuel: 4800,
    dateDebut: '2019-09-01',
    joursCongesRestants: 18,
    statut: 'actif',
  },
  {
    identifiant: 'emp-3',
    matricule: 'EMP-003',
    nomComplet: 'David Hawthorne',
    poste: 'Chief Financial Officer',
    departement: 'Comptabilite',
    typeContrat: 'CDI',
    salaireMensuel: 5600,
    dateDebut: '2018-03-15',
    joursCongesRestants: 15,
    statut: 'actif',
  },
  {
    identifiant: 'emp-4',
    matricule: 'EMP-004',
    nomComplet: 'Hannah Campbell',
    poste: 'Head Librarian & Archivist',
    departement: 'Services',
    typeContrat: 'CDI',
    salaireMensuel: 3900,
    dateDebut: '2021-01-10',
    joursCongesRestants: 25,
    statut: 'actif',
  },
];

export const DEMANDES_CONGES_INITIALES: DemandeConge[] = [
  {
    identifiant: 'cg-1',
    identifiantEmploye: 'emp-2',
    nomEmploye: 'Prof. Evelyn Reed',
    typeConge: 'annuel',
    dateDebut: '2026-04-14',
    dateFin: '2026-04-18',
    motif: 'Academic conference research trip and sabbatical rest',
    statut: 'approuve',
  },
  {
    identifiant: 'cg-2',
    identifiantEmploye: 'emp-4',
    nomEmploye: 'Hannah Campbell',
    typeConge: 'maladie',
    dateDebut: '2026-03-18',
    dateFin: '2026-03-20',
    motif: 'Medical dental surgery recovery',
    statut: 'en_attente',
  },
];

export const LIVRES_INITIAUX: LivreBibliotheque[] = [
  {
    identifiant: 'liv-1',
    isbn: '978-0134685991',
    titre: 'Calculus: Early Transcendentals',
    auteur: 'James Stewart',
    categorie: 'Mathematics & STEM',
    exemplairesTotal: 15,
    exemplairesDisponibles: 11,
    emplacement: 'Shelf A-14',
  },
  {
    identifiant: 'liv-2',
    isbn: '978-0062316097',
    titre: 'Sapiens: A Brief History of Humankind',
    auteur: 'Yuval Noah Harari',
    categorie: 'History & Humanities',
    exemplairesTotal: 8,
    exemplairesDisponibles: 4,
    emplacement: 'Shelf C-02',
  },
  {
    identifiant: 'liv-3',
    isbn: '978-0131103627',
    titre: 'The C Programming Language',
    auteur: 'Brian Kernighan, Dennis Ritchie',
    categorie: 'Computer Science',
    exemplairesTotal: 6,
    exemplairesDisponibles: 2,
    emplacement: 'Shelf E-08',
  },
  {
    identifiant: 'liv-4',
    isbn: '978-0451524935',
    titre: '1984',
    auteur: 'George Orwell',
    categorie: 'Literature & Fiction',
    exemplairesTotal: 20,
    exemplairesDisponibles: 17,
    emplacement: 'Shelf B-09',
  },
];

export const EMPRUNTS_INITIAUX: EmpruntLivre[] = [
  {
    identifiant: 'emp-liv-1',
    identifiantLivre: 'liv-1',
    titreLivre: 'Calculus: Early Transcendentals',
    emprunteurNom: 'Marcus Vance',
    emprunteurType: 'eleve',
    dateEmprunt: '2026-03-01',
    dateRetourPrevue: '2026-03-22',
    statut: 'en_cours',
  },
  {
    identifiant: 'emp-liv-2',
    identifiantLivre: 'liv-3',
    titreLivre: 'The C Programming Language',
    emprunteurNom: 'Prof. Evelyn Reed',
    emprunteurType: 'professeur',
    dateEmprunt: '2026-02-15',
    dateRetourPrevue: '2026-03-01',
    statut: 'en_retard',
  },
];

export const ANNONCES_INITIALES: AnnonceCommunication[] = [
  {
    identifiant: 'ann-1',
    titre: 'Upcoming Term 2 Parent-Teacher Conferences',
    contenu: 'The official Spring Semester Parent-Teacher meetings will take place on Friday, March 27, 2026. Schedule your 15-minute consultations via the parent portal.',
    auteurNom: 'Julian Mercer (Communications Director)',
    datePublication: '2026-03-11',
    cible: 'parents',
    priorite: 'importante',
  },
  {
    identifiant: 'ann-2',
    titre: 'Annual STEM & Science Fair Submissions Open',
    contenu: 'All Grade 10 to 12 students are invited to register their science fair team projects by March 30. High-value scholarship awards will be granted to the top 3 innovations.',
    auteurNom: 'Prof. Evelyn Reed',
    datePublication: '2026-03-09',
    cible: 'eleves',
    priorite: 'normale',
  },
  {
    identifiant: 'ann-3',
    titre: 'Campus Fiber Network Maintenance Alert',
    contenu: 'Scheduled core network upgrades this Saturday from 02:00 AM to 06:00 AM UTC. Portal access will remain accessible with temporary latency.',
    auteurNom: 'IT Infrastructure Division',
    datePublication: '2026-03-12',
    cible: 'tous',
    priorite: 'urgente',
  },
];
