import {
  MessageChatProfesseur,
  MessageAdministrationEleve,
  EvenementCalendrierScolaire,
  CompteCantineBadge,
  CarteTransportScolaire,
  CorrectionExamenDetaillee,
  JustificatifAbsence,
  ProfilEleveComplet,
  SujetForumClasse,
  EbookNumerique,
} from '../typesEtendus';

export const PROFIL_ELEVE_INITIAL: ProfilEleveComplet = {
  identifiant: 'el-1',
  matricule: 'STU-2026-001',
  nomComplet: 'Marcus Vance',
  avatarUrl: '',
  dateNaissance: '2009-04-12',
  lieuNaissance: 'Paris, France',
  sexe: 'M',
  classe: '1ère C',
  delegueClasse: true,
  specialites: ['Mathématiques Approfondies', 'Physique-Chimie', 'Sciences de l’Ingénieur'],
  languesVivantes: ['Anglais (LV1 - C1)', 'Espagnol (LV2 - B2)'],
  courriel: 'm.vance@student.academy.edu',
  telephone: '+33 6 12 34 56 78',
  adresse: '14 Avenue des Tilleuls, 75016 Paris',
  regimeScolaire: 'Demi-pensionnaire',
  contactUrgence: {
    nom: 'Eleanor Vance',
    lienParente: 'Mère / Tutrice légale',
    telephone: '+33 6 98 76 54 32',
    courriel: 'eleanor.vance@vance-holding.com',
  },
  medecinTraitant: 'Dr. Philippe Martin (01 42 68 00 11)',
  allergiesAmenagements: 'Allergie arachides (PAI actif à l’infirmerie) & Tiers-temps non requis.',
};

export const MESSAGES_CHAT_PROFESSEURS_INITIAUX: MessageChatProfesseur[] = [
  {
    identifiant: 'msg-1',
    destinataireId: 'prof-1',
    destinataireNom: 'Prof. Evelyn Reed',
    expediteurNom: 'Marcus Vance',
    expediteurRole: 'eleve',
    matiere: 'Mathématiques',
    contenu: 'Bonjour Professeur, pour l’exercice 24 du devoir de calcul intégral, faut-il intégrer deux fois par parties ou poser un changement de variable ?',
    dateEnvoi: '2026-03-04',
    heureEnvoi: '17:42',
    lu: true,
  },
  {
    identifiant: 'msg-2',
    destinataireId: 'prof-1',
    destinataireNom: 'Prof. Evelyn Reed',
    expediteurNom: 'Prof. Evelyn Reed',
    expediteurRole: 'professeur',
    matiere: 'Mathématiques',
    contenu: 'Bonjour Marcus. Une double intégration par parties est la méthode la plus directe. Pensez à bien expliciter vos dérivées intermédiaires.',
    dateEnvoi: '2026-03-04',
    heureEnvoi: '18:15',
    lu: true,
    fichierJoint: {
      nom: 'indication_calcul_ex24.pdf',
      taille: '142 KB',
    },
  },
  {
    identifiant: 'msg-3',
    destinataireId: 'prof-2',
    destinataireNom: 'Dr. Robert Chen',
    expediteurNom: 'Marcus Vance',
    expediteurRole: 'eleve',
    matiere: 'Physique & Chimie',
    contenu: 'Docteur Chen, le compte-rendu du TP sur l’interféromètre de Michelson doit-il inclure les barres d’incertitude expérimentale sur le tracé Regressi ?',
    dateEnvoi: '2026-03-05',
    heureEnvoi: '09:20',
    lu: true,
  },
  {
    identifiant: 'msg-4',
    destinataireId: 'prof-2',
    destinataireNom: 'Dr. Robert Chen',
    expediteurNom: 'Dr. Robert Chen',
    expediteurRole: 'professeur',
    matiere: 'Physique & Chimie',
    contenu: 'Oui tout à fait. Utilisez l’écart-type de répétabilité à 95% de confiance (k=2). Les graphiques sans barres d’erreur perdront 1.5 point.',
    dateEnvoi: '2026-03-05',
    heureEnvoi: '11:05',
    lu: true,
  },
  {
    identifiant: 'msg-5',
    destinataireId: 'prof-3',
    destinataireNom: 'Sarah Jenkins',
    expediteurNom: 'Sarah Jenkins',
    expediteurRole: 'professeur',
    matiere: 'Littérature & Français',
    contenu: 'Rappel pour la classe : la dissertation sur Les Fleurs du Mal doit être déposée sur l’espace numérique avant vendredi 23h59.',
    dateEnvoi: '2026-03-06',
    heureEnvoi: '08:30',
    lu: false,
  },
];

export const MESSAGES_ADMINISTRATION_INITIAUX: MessageAdministrationEleve[] = [
  {
    identifiant: 'adm-msg-1',
    titre: 'Convocation aux Épreuves Communes de Contrôle Continu (E3C)',
    expediteurService: 'Direction des Études',
    date: '2026-03-05',
    priorite: 'officiel',
    contenu: 'Marcus, votre convocation officielle pour les épreuves du second trimestre est disponible. Vous composerez en Salle Polyvalente B12 à 08h00.',
    lu: true,
    actionRequise: 'Émarger et imprimer la convocation',
    documentAttache: 'Convocation_Officielle_E3C_Vance_Marcus.pdf',
  },
  {
    identifiant: 'adm-msg-2',
    titre: 'Validation de votre réinscription en Terminale S & Choix des spécialités',
    expediteurService: 'Secrétariat Général',
    date: '2026-03-03',
    priorite: 'urgente',
    contenu: 'Le formulaire de voeux définitifs pour la classe de Terminale (abandon d’une spécialité et maintien de 2 majeures) doit être visé par vos parents avant le 25 mars.',
    lu: true,
    actionRequise: 'Confirmation parentale en ligne requise',
  },
  {
    identifiant: 'adm-msg-3',
    titre: 'Campagne de Santé Scolaire : Visite Médicale PAI',
    expediteurService: 'Infirmerie',
    date: '2026-02-28',
    priorite: 'normale',
    contenu: 'Renouvellement annuel du protocole d’accueil individualisé pour allergie. Rendez-vous fixé le mardi 17 mars à 10h15 à l’infirmerie.',
    lu: false,
  },
];

export const EVENEMENTS_CALENDRIER_SCOLAIRE: EvenementCalendrierScolaire[] = [
  {
    identifiant: 'cal-1',
    titre: 'Vacances d’Hiver (Zone C)',
    type: 'vacances',
    dateDebut: '2026-02-14',
    dateFin: '2026-03-02',
    description: 'Fermeture pédagogique de l’établissement.',
    concerne: 'Tous les niveaux',
  },
  {
    identifiant: 'cal-2',
    titre: 'Semaine d’Évaluations et Devoirs Communs',
    type: 'examen',
    dateDebut: '2026-03-16',
    dateFin: '2026-03-20',
    description: 'Épreuves écrites surveillées en conditions d’examen pour les classes de Première et Terminale.',
    lieu: 'Grand Hall & Bâtiment Sciences',
    concerne: '1ères & Terminales',
  },
  {
    identifiant: 'cal-3',
    titre: 'Conseil de Classe du 2e Trimestre',
    type: 'conseil_classe',
    dateDebut: '2026-03-24',
    description: 'Délibération trimestrielle de la 1ère C avec les délégués élèves et représentants parents.',
    lieu: 'Salle du Conseil (18h00)',
    concerne: 'Classe 1ère C',
  },
  {
    identifiant: 'cal-4',
    titre: 'Journée Portes Ouvertes & Forum des Grandes Écoles',
    type: 'evenement_culturel',
    dateDebut: '2026-04-04',
    description: 'Rencontre avec les anciens élèves, prépas CPGE et universités partenaires.',
    lieu: 'Campus Principal',
    concerne: 'Lycéens et Familles',
  },
  {
    identifiant: 'cal-5',
    titre: 'Lundi de Pâques (Férié)',
    type: 'ferie',
    dateDebut: '2026-04-06',
    description: 'Jour férié légal. Établissement fermé.',
    concerne: 'Tous',
  },
  {
    identifiant: 'cal-6',
    titre: 'Vacances de Printemps',
    type: 'vacances',
    dateDebut: '2026-04-18',
    dateFin: '2026-05-04',
    description: 'Période de congés scolaires du printemps.',
    concerne: 'Tous les niveaux',
  },
];

export const COMPTE_CANTINE_INITIAL: CompteCantineBadge = {
  soldeActuel: 68.50,
  numeroBadge: 'BDG-75016-889',
  regime: 'demi_pensionnaire',
  forfaitRestant: 14,
  derniersPassages: [
    { id: 'pas-1', date: '2026-03-06', heure: '12:24', typeRepas: 'Déjeuner Équilibré (Plateau Chaud)', debit: 4.80, borne: 'Borne Self #2' },
    { id: 'pas-2', date: '2026-03-05', heure: '12:18', typeRepas: 'Déjeuner Menu Végétarien Bio', debit: 4.80, borne: 'Borne Self #1' },
    { id: 'pas-3', date: '2026-03-03', heure: '12:30', typeRepas: 'Déjeuner Complet + Dessert Fruit', debit: 4.80, borne: 'Borne Self #3' },
    { id: 'pas-4', date: '2026-03-02', heure: '12:15', typeRepas: 'Déjeuner Plat du Chef', debit: 4.80, borne: 'Borne Self #2' },
  ],
};

export const CARTE_TRANSPORT_INITIALE: CarteTransportScolaire = {
  numeroCarte: 'BUS-IDFM-2026-9921',
  ligneBus: 'Ligne Express Scolaire #14 - Circuit Ouest',
  arretPrincipal: 'Station Mairie du 16e - Lycée International',
  statutValidite: 'valide',
  dateExpiration: '2026-07-10',
};

export const CORRECTIONS_EXAMENS_INITIALES: CorrectionExamenDetaillee[] = [
  {
    identifiant: 'cor-1',
    titreEvaluation: 'Devoir Surveillé #3 : Équations Différentielles & Séries',
    matiere: 'Mathématiques',
    dateExamen: '2026-02-25',
    noteObtenue: 18.5,
    noteMaximale: 20,
    moyenneClasse: 13.8,
    noteMin: 8.0,
    noteMax: 19.5,
    rangEleve: 2,
    effectifTotal: 28,
    appreciationProfesseur: 'Excellente copie ! Rigueur remarquable dans la justification de l’existence des solutions et la démonstration du théorème d’unicité.',
    baremeDetaille: [
      { question: 'Partie A : Résolution de l’équation homogène', pointsObtenus: 5, totalPoints: 5, commentaire: 'Parfait. Méthode du discriminant bien rédigée.' },
      { question: 'Partie B : Recherche de la solution particulière', pointsObtenus: 4.5, totalPoints: 5, commentaire: 'Très bien. Petite simplification trigonométrique omise à l’étape 3.' },
      { question: 'Partie C : Problème de Cauchy et limite en +∞', pointsObtenus: 5, totalPoints: 5, commentaire: 'Démonstration limpide.' },
      { question: 'Partie D : Application physique au circuit RLC amorti', pointsObtenus: 4, totalPoints: 5, commentaire: 'Interprétation graphique correcte, unité oubliée sur le facteur de qualité Q.' },
    ],
    copieScanneNom: 'Copie_Scanne_Vance_Marcus_DS3_Maths.pdf',
    corrigeTypeNom: 'Corrige_Type_Officiel_DS3_Maths_2026.pdf',
  },
  {
    identifiant: 'cor-2',
    titreEvaluation: 'Examen Blanc : Optique Ondulatoire & Lois de Snell-Descartes',
    matiere: 'Physique & Chimie',
    dateExamen: '2026-02-18',
    noteObtenue: 17.0,
    noteMaximale: 20,
    moyenneClasse: 12.4,
    noteMin: 6.5,
    noteMax: 18.0,
    rangEleve: 3,
    effectifTotal: 28,
    appreciationProfesseur: 'Très bon devoir. Les calculs d’incertitudes sont bien maîtrisés. Attention à la précision du schéma de réfraction.',
    baremeDetaille: [
      { question: 'Exercice 1 : Réfraction et angle limite', pointsObtenus: 6, totalPoints: 6, commentaire: 'Impeccable.' },
      { question: 'Exercice 2 : Réseau de diffraction et spectre lumineux', pointsObtenus: 5.5, totalPoints: 6, commentaire: 'Calcul de la longueur d’onde exact.' },
      { question: 'Exercice 3 : Interférences lumineuses à 2 ondes', pointsObtenus: 5.5, totalPoints: 8, commentaire: 'L’expression de l’interfrange est juste mais l’allure d’intensité manque de graduations.' },
    ],
    copieScanneNom: 'Copie_Scanne_Vance_Marcus_Exam_Physique.pdf',
    corrigeTypeNom: 'Corrige_Type_Optique_Ondulatoire.pdf',
  },
  {
    identifiant: 'cor-3',
    titreEvaluation: 'Commentaire Composé : Baudelaire - L’Albatros',
    matiere: 'Français & Littérature',
    dateExamen: '2026-02-10',
    noteObtenue: 16.0,
    noteMaximale: 20,
    moyenneClasse: 13.1,
    noteMin: 9.0,
    noteMax: 17.5,
    rangEleve: 4,
    effectifTotal: 28,
    appreciationProfesseur: 'Devoir très stimulant. L’analyse des figures de style et du statut du poète maudit est particulièrement fine.',
    baremeDetaille: [
      { question: 'Axe I : La condition tragique du poète déchu', pointsObtenus: 5.5, totalPoints: 7, commentaire: 'Bonnes citations, transition fluide.' },
      { question: 'Axe II : Le double registre épique et satirique', pointsObtenus: 5.5, totalPoints: 7, commentaire: 'Structure d’antithèse bien analysée.' },
      { question: 'Introduction, Conclusion et Qualité de la langue', pointsObtenus: 5.0, totalPoints: 6, commentaire: 'Vocabulaire riche, excellente orthographe.' },
    ],
    copieScanneNom: 'Copie_Scanne_Vance_Marcus_Francais_Baudelaire.pdf',
    corrigeTypeNom: 'Plan_Detaille_Corrige_Baudelaire.pdf',
  },
];

export const JUSTIFICATIFS_ABSENCES_INITIAUX: JustificatifAbsence[] = [
  {
    identifiant: 'just-1',
    dateAbsenceDebut: '2026-02-12',
    dateAbsenceFin: '2026-02-12',
    nombreHeures: 4,
    motif: 'maladie',
    commentaire: 'Syndrome grippal avec consultation chez le médecin traitant.',
    nomFichierJoint: 'certificat_medical_dr_martin_12fev2026.pdf',
    dateDepot: '2026-02-13',
    statut: 'valide_vie_scolaire',
    reponseVieScolaire: 'Justificatif conforme enregistré par le service Vie Scolaire.',
  },
  {
    identifiant: 'just-2',
    dateAbsenceDebut: '2026-03-01',
    dateAbsenceFin: '2026-03-01',
    nombreHeures: 2,
    motif: 'transport',
    commentaire: 'Panne d’alimentation électrique sur la ligne de RER / Bus du matin.',
    nomFichierJoint: 'bulletin_retard_sncf_idfm.pdf',
    dateDepot: '2026-03-01',
    statut: 'valide_vie_scolaire',
    reponseVieScolaire: 'Incident de transport vérifié et validé.',
  },
];

export const SUJETS_FORUM_CLASSE_INITIAUX: SujetForumClasse[] = [
  {
    identifiant: 'forum-1',
    auteurNom: 'Marcus Vance',
    auteurRole: 'delegue',
    matiere: 'Mathématiques',
    titre: 'Fiche récapitulative : Formules de dérivation & Intégration pour le DS de lundi',
    contenu: 'Salut la classe ! J’ai synthétisé les théorèmes clés du chapitre 4 (développements limités, IPP, équations différentielles d’ordre 1 et 2). Voici le fichier pour nos révisions en groupe.',
    dateCreation: '2026-03-05',
    resolu: true,
    reponses: [
      {
        identifiant: 'rep-1',
        auteurNom: 'Sophia Martinez',
        date: '2026-03-05 19:10',
        contenu: 'Merci Marcus ! Ton tableau récapitulatif sur les solutions des équations sans second membre est super clair.',
        estMeilleureReponse: true,
      },
      {
        identifiant: 'rep-2',
        auteurNom: 'Prof. Evelyn Reed',
        date: '2026-03-06 08:45',
        contenu: 'Bravo Marcus pour cette initiative de travail collaboratif. N’oubliez pas de bien vérifier le signe dans la formule d’intégration par parties !',
      },
    ],
  },
  {
    identifiant: 'forum-2',
    auteurNom: 'Alexandre Meyer',
    auteurRole: 'eleve',
    matiere: 'Physique & Chimie',
    titre: 'Question TP Michelson : valeur de la longueur d’onde du laser He-Ne',
    contenu: 'Est-ce que quelqu’un a trouvé une valeur proche de 632.8 nm avec les anneaux d’interférence ? Notre binôme trouve 628 nm.',
    dateCreation: '2026-03-04',
    resolu: true,
    reponses: [
      {
        identifiant: 'rep-3',
        auteurNom: 'Marcus Vance',
        date: '2026-03-04 18:20',
        contenu: 'Oui Alexandre, 628 nm donne un écart relatif de seulement 0.76%, ce qui est tout à fait acceptable avec le vernier manuel.',
        estMeilleureReponse: true,
      },
    ],
  },
  {
    identifiant: 'forum-3',
    auteurNom: 'Chloe Dubois',
    auteurRole: 'eleve',
    matiere: 'Vie de Classe',
    titre: 'Organisation de la visite du CERN et voyage scientifique de fin d’année',
    contenu: 'Nous avons reçu l’accord de principe pour la visite de Genève en mai. Sondage pour le choix des visites annexes (musée d’histoire des sciences ou observatoire).',
    dateCreation: '2026-03-02',
    resolu: false,
    reponses: [
      {
        identifiant: 'rep-4',
        auteurNom: 'Gabriel Traore',
        date: '2026-03-03 14:00',
        contenu: 'Je vote pour l’Observatoire astronomique !',
      },
    ],
  },
];

export const EBOOKS_NUMERIQUES_INITIAUX: EbookNumerique[] = [
  {
    identifiant: 'ebk-1',
    titre: 'Manuel de Mathématiques Approfondies - 1ère Spécialité',
    auteur: 'Pr. Laurent Schwartz & Collège Académique',
    matiere: 'Mathématiques',
    format: 'PDF',
    taille: '18.4 MB',
    niveau: '1ère S / 1ère C',
    nombrePages: 384,
    description: 'Cours complet avec 650 exercices corrigés, méthodes de démonstration et problèmes de synthèse.',
    disponibleLecture: true,
    lecturesEnCours: true,
  },
  {
    identifiant: 'ebk-2',
    titre: 'Physique XXI : Ondes, Matière et Énergie',
    auteur: 'Dr. Raymond Serway & Robert Chen',
    matiere: 'Physique & Chimie',
    format: 'PDF',
    taille: '24.2 MB',
    niveau: 'Lycée Scientifique',
    nombrePages: 420,
    description: 'Guide de référence pour les travaux pratiques, optique ondulatoire et thermodynamique moderne.',
    disponibleLecture: true,
    lecturesEnCours: true,
  },
  {
    identifiant: 'ebk-3',
    titre: 'Anthologie Critique des Grands Textes Littéraires',
    auteur: 'Sarah Jenkins & Académie des Lettres',
    matiere: 'Français',
    format: 'EPUB',
    taille: '8.1 MB',
    niveau: '1ère Générale',
    nombrePages: 290,
    description: 'Textes intégraux annotés des œuvres au programme du baccalauréat de français.',
    disponibleLecture: true,
    lecturesEnCours: false,
  },
  {
    identifiant: 'ebk-4',
    titre: 'Atlas Historique et Géopolitique du Monde Contemporain',
    auteur: 'M. Jean-Paul Durand',
    matiere: 'Histoire-Géo',
    format: 'PDF',
    taille: '32.6 MB',
    niveau: '1ère & Terminale',
    nombrePages: 210,
    description: 'Cartes haute définition, chronologies et fiches de révision pour les concours et examens.',
    disponibleLecture: true,
    lecturesEnCours: false,
  },
];
