export const TRADUCTIONS_FR_MODULES = {
  // Tableau de bord
  titreTableauDeBord: 'Tableau de Bord Opérationnel',
  descriptionTableauDeBord: 'Suivi en temps réel des élèves, enseignants, finances et infrastructures.',
  nouvelleInscription: 'Nouvelle Inscription',
  elevesInscrits: 'Élèves Inscrits',
  repartitionCohortes: 'Actifs sur 4 cohortes',
  corpsEnseignant: 'Corps Enseignant',
  enseignantsComplets: 'Programme pédagogique complet',
  recouvrementFrais: 'Recouvrement des Frais',
  tauxDeRecouvrement: 'taux de recouvrement',
  inventaireBibliotheque: 'Inventaire Bibliothèque',
  exemplairesEnRayon: 'Exemplaires en rayon',
  emploiDuTempsDuJour: 'Emploi du Temps du Jour',
  horairesEtSalles: 'Horaires des cours et salles assignées',
  avisOfficiels: 'Avis Officiels',
  enDirect: 'En direct',
  ouvrirCommunication: 'Ouvrir l’Espace Communication',

  // Administration
  titreAdministration: 'Administration Institutionnelle',
  descriptionAdministration: 'Configuration des cohortes, tuteurs, accès et politiques académiques.',
  parametresAcademiques: 'Paramètres Académiques',
  sessionAcademique: 'Session Académique',
  cohortesActives: 'Cohortes Actives',
  capaciteCohortes: '4 Classes • 108 Places',
  conformiteSecurite: 'Conformité & Sécurité',
  normeSecurite: 'Certifié ISO-27001',
  repartitionClassesTitre: 'Répartition des Classes & Cohortes',
  repartitionClassesDesc: 'Salles de classe, professeurs principaux et effectifs',
  classeCohorte: 'Classe Cohorte',
  salleAssignee: 'Salle Assignée',
  professeurPrincipal: 'Professeur Principal',
  effectifEleves: 'Effectif',
  statut: 'Statut',
  actif: 'Actif',

  // Professeurs & Notes
  titreProfesseurs: 'Espace Enseignants & Carnet de Notes',
  descriptionProfesseurs: 'Saisie des notes d’évaluation, appel de présence et appréciations.',
  faireAppel: 'Faire l’Appel',
  saisirNote: 'Saisir une Note',
  registreNotes: 'Registre des Évaluations',
  registreNotesDesc: 'Contrôles continus, travaux pratiques et examens',
  toutesLesClasses: 'Toutes les cohortes',
  nomEleve: 'Nom de l’Élève',
  classe: 'Classe',
  matiereEtTitre: 'Matière & Évaluation',
  note: 'Note',
  date: 'Date',
  appreciation: 'Appréciation',
  aucuneAppreciation: 'Aucune appréciation enregistrée.',

  // Élèves
  titreEleves: 'Inscriptions & Dossiers Élèves',
  descriptionEleves: 'Profils académiques, moyennes générales, contacts parents et frais de scolarité.',
  inscrireNouvelEleve: 'Inscrire un Élève',
  effectifInscrit: 'Effectif des Élèves Inscrits',
  rechercheMatricule: 'Rechercher nom ou matricule...',
  matriculeEtNom: 'Matricule & Nom',
  contactParent: 'Contact Parent / Tuteur',
  moyenneGenerale: 'Moyenne Générale',
  presence: 'Présence',
  statutScolarite: 'Scolarité',
  soldeRegle: 'Soldé',
  soldePartiel: 'Partiel',
  enRetard: 'En retard',

  // Parents
  titreParents: 'Portail des Parents & Tuteurs',
  descriptionParents: 'Suivi des résultats, assiduité et paiement en ligne des frais de scolarité.',
  eleveSelectionne: 'Élève actif :',
  contacterProfesseur: 'Contacter l’Enseignant',
  derniersResultats: 'Derniers Résultats d’Évaluations',
  relevesFrais: 'Factures & Frais de Scolarité',
  echeanceLe: 'Échéance le',
  resteAPayer: 'Reste :',
  payerFrais: 'Régler la Scolarité',

  // Comptabilité
  titreComptabilite: 'Gestion Financière & Économat',
  descriptionComptabilite: 'Facturation des frais scolaires, dépenses de fonctionnement et trésorerie.',
  enregistrerTransaction: 'Enregistrer une Transaction',
  genererFacture: 'Générer une Facture',
  totalFacture: 'Total Facturé',
  recettesEncaissees: 'Recettes Encaissées',
  impayesRestants: 'Soldes Impayés',
  facturesEleves: 'Factures de Scolarité Élèves',
  journalFinancier: 'Journal Général de Trésorerie',
  type: 'Type',
  categorie: 'Catégorie',
  montant: 'Montant',
  depense: 'Dépense',
  revenu: 'Revenu',

  // Ressources Humaines
  titreRH: 'Ressources Humaines & Personnel',
  descriptionRH: 'Contrats de travail, masse salariale mensuelle et gestion des congés.',
  demanderConge: 'Demander un Congé',
  ajouterPersonnel: 'Ajouter un Collaborateur',
  personnelActif: 'Personnel Actif',
  masseSalariale: 'Masse Salariale Mensuelle',
  congesEnAttente: 'Congés en Attente',
  annuairePersonnel: 'Annuaire du Personnel & Corps Enseignant',
  posteEtDepartement: 'Poste & Département',
  contrat: 'Contrat',
  salaireMensuel: 'Salaire Mensuel',
  demandesCongesTitre: 'Demandes de Congés & Absences',

  // Bibliothèque
  titreBibliotheque: 'Bibliothèque & Ressources Pédagogiques',
  descriptionBibliotheque: 'Catalogue des ouvrages, gestion des emprunts et inventaire des rayons.',
  nouvelEmprunt: 'Enregistrer un Emprunt',
  ajouterLivre: 'Ajouter un Ouvrage',
  totalOuvrages: 'Total des Ouvrages',
  exemplairesDispo: 'Disponibles en Rayon',
  empruntsActifs: 'Emprunts en Cours',
  catalogueLivres: 'Catalogue des Livres',
  rechercheLivre: 'Rechercher titre, auteur ou ISBN...',
  titreEtAuteur: 'Titre & Auteur',
  emplacement: 'Emplacement',
  disponibilite: 'Disponibilité',
  suiviEmprunts: 'Suivi des Emprunts en Cours',
  emprunteur: 'Emprunteur',
  dateRetourPrevue: 'Retour prévu le',
  titre: 'Titre',
  auteur: 'Auteur',
  catalogueOuvrages: 'Catalogue des Ouvrages',
  exemplairesDisponibles: 'Exemplaires Disponibles',
  disponible: 'disponible',
  empruntsEnCours: 'Emprunts en Cours',
  emprunterLivre: 'Emprunter un Livre',
  fondsDocumentaire: 'Fonds Documentaire',
  disponiblesEnRayon: 'Disponibles en Rayon',
  nombreTotalExemplaires: 'Nombre Total d’Exemplaires',

  // Communication
  titreCommunication: 'Communications & Diffusion Institutionnelle',
  descriptionCommunication: 'Circulaires officielles, alertes urgentes et annonces communautaires.',
  nouvelleCirculaire: 'Publier une Circulaire',
  bulletinsActifs: 'Bulletins Actifs',
  diffusionsParents: 'Diffusions Parents',
  alertesUrgentes: 'Alertes d’Urgence',
  filCirculaires: 'Fil des Circulaires & Notes Officielles',
  publicCible: 'Public cible :',
  priorite: 'Priorité',
  publiePar: 'Émis par :',
  fluxAnnonces: 'Flux des Annonces du Campus',
  publierAnnonce: 'Publier une Annonce',
  destinataire: 'Destinataire',

  // Tableaux de Bord par Rôle
  coursDuJour: 'Mes Cours du Jour',
  evaluationsRecentes: 'Évaluations Récemment Saisies',
  effectifTotalEnseigne: 'Élèves Supervisés',
  classesAssigneesTitre: 'Classes Assignées',
  tauxAssiduiteMoyen: 'Taux de Présence Moyen',
  mesNotes: 'Mes Dernières Notes',
  mesCours: 'Mon Emploi du Temps',
  mesLivresEmpruntes: 'Mes Emprunts de Livres',
  fraisScolaires: 'Statut de Scolarité',
  tauxPresence: 'Taux d’Assiduité',
  suiviScolaireEnfant: 'Suivi Académique de l’Élève',
  reglerSolde: 'Régler le Solde de Scolarité',
  contacterEnseignant: 'Contacter le Professeur',
  prochaineEcheance: 'Prochaine Échéance',
  statistiquesFinancieres: 'Synthèse Financière Globale',
  facturesImpayees: 'Factures en Attente de Paiement',
  dernieresTransactions: 'Dernières Opérations Financières',
  tauxPaiement: 'Performance de Recouvrement',
  syntheseRH: 'Synthèse du Personnel & Contrats',
  demandesAValider: 'Demandes de Congé en Attente',
  effectifActif: 'Effectif Salarié Actif',
  masseSalarialeMensuelle: 'Masse Salariale Mensuelle',
  etatFondsDocumentaire: 'État du Fonds Documentaire',
  empruntsEnRetardTitre: 'Ouvrages en Retard de Restitution',
  titresPopulaires: 'Volumes en Rayon',
  syntheseCommunications: 'Gestion des Diffusions Institutionnelles',
  diffusionsRecentes: 'Derniers Avis Transmis',
  alertesCritiques: 'Alertes Urgentes Publiées',
};
