export const TRADUCTIONS_FR_NAVIGATION = {
  // Entete & Navigation
  nomEtablissement: 'Académie Saint Jude',
  sousTitreEtablissement: 'Système de Gestion Académique & Administrative',
  recherchePlaceholder: 'Rechercher élèves, professeurs, factures, livres...',
  noticesEtBulletins: 'Avis & Bulletins',
  fermer: 'Fermer',
  changerRole: 'Changer de rôle',
  anneeScolaire: 'Année Académique 2025–2026',
  trimestreActif: 'Trimestre 2 Actif',
  droitsReserves: 'Tous droits réservés.',
  editionEntreprise: 'Portail de Gestion Académique • Édition Établissement',

  // Rôles
  role_administrateur: 'Directeur / Administration',
  role_professeur: 'Professeur & Enseignant',
  role_eleve: 'Portail Élève',
  role_parent: 'Parent & Tuteur',
  role_secretaire: 'Secrétariat & Scolarité',
  role_comptable: 'Comptabilité & Économe',
  role_ressources_humaines: 'Ressources Humaines',
  role_bibliothecaire: 'Bibliothécaire',
  role_charge_communication: 'Communication',

  // Modules
  module_tableau_de_bord: 'Tableau de bord',
  module_administration: 'Administration',
  module_professeurs: 'Professeurs & Notes',
  module_eleves: 'Dossiers Élèves',
  module_parents: 'Espace Parents',
  module_comptabilite: 'Comptabilité & Frais',
  module_ressources_humaines: 'Ressources Humaines',
  module_bibliotheque: 'Bibliothèque',
  module_communication: 'Communications',

  // Navigation contextuelle par role
  menu_tableau_de_bord: 'Tableau de bord',
  menu_administration: 'Administration',
  menu_comptabilite_frais: 'Comptabilité & Frais',
  menu_ressources_humaines: 'Ressources Humaines',
  menu_communications: 'Communications',
  menu_mes_classes: 'Mes Classes',
  menu_grading_marks: 'Grading & Marks',
  menu_ressources_pedagogiques: 'Ressources Pédagogiques',
  menu_mes_cours: 'Mes Cours',
  menu_mes_notes: 'Mes Notes',
  menu_devoirs_examens: 'Devoirs & Examens',
  menu_ressources_eleves: 'Ressources Élèves',
  menu_suivi_enfant: 'Suivi Enfant',
  menu_absences_justificatifs: 'Absences & Justificatifs',
  menu_moyennes_resultats: 'Moyennes & Résultats',
  menu_dossiers_eleves: 'Dossiers Élèves',
  menu_inscriptions: 'Inscriptions',
  menu_calendrier_horaires: 'Calendrier & Horaires',
  menu_administratif: 'Administratif',
  menu_budgets: 'Budgets',
  menu_rapports_financiers: 'Rapports Financiers',
  menu_paie: 'Paie',
  menu_gestion_personnel: 'Gestion du Personnel',
  menu_catalogue_bibliotheque: 'Catalogue Bibliothèque',
  menu_emprunts_retours: 'Emprunts & Retours',
  menu_ressources_numeriques: 'Ressources Numériques',
  menu_actualites: 'Actualités',
  menu_annonces: 'Annonces',
  menu_medias: 'Médias',

  // Boutons Communs
  enregistrer: 'Enregistrer',
  annuler: 'Annuler',
  voirTout: 'Voir tout',
  ajouter: 'Ajouter',
  rechercher: 'Rechercher',
  payer: 'Payer',
  envoyer: 'Envoyer',
  approuver: 'Approuver',
  rejeter: 'Rejeter',
  rendreLivre: 'Marquer comme rendu',
};
